@echo off
:: ============================================================
:: keilkill.bat - Clean Keil MDK build artifacts
:: Run this script in the project root directory to remove
:: temporary and intermediate build files (*.bak, *.o, *.axf,
:: *.map, etc.) generated by the Keil compiler/linker.
:: ============================================================

del *.bak /s
del *.ddk /s
del *.edk /s
del *.lst /s
del *.lnp /s
del *.mpf /s
del *.mpj /s
del *.obj /s
del *.omf /s
::del *.opt /s  :: keep J-Link debugger settings (do not delete)
del *.plg /s
del *.rpt /s
del *.tmp /s
del *.__i /s
del *.crf /s
del *.o /s
del *.d /s
del *.axf /s
del *.tra /s
del *.dep /s
del JLinkLog.txt /s

del *.iex /s
del *.htm /s
::del *.sct /s
del *.map /s
exit
